/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.31
 * Generated at: 2018-09-01 06:41:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class my_005forder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>我的订单</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/shopping-mall-index.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/zhonglin.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"position:relative;\">\r\n");
      out.write("\r\n");
      out.write("    \t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write("\r\n");
      out.write("    \t\r\n");
      out.write("    \t<div class=\"order-right f-r\">\r\n");
      out.write("        \t<div class=\"order-hd\">\r\n");
      out.write("            \t<dl class=\"f-l\">\r\n");
      out.write("                \t<dt>\r\n");
      out.write("                    \t<a href=\"#\"><img src=\"images/data-tu2.gif\" /></a>\r\n");
      out.write("                    </dt>\r\n");
      out.write("                    <dd>\r\n");
      out.write("                    \t<h3><a href=\"#\">RH了</a></h3>\r\n");
      out.write("                        <p>zhao601884596</p>\r\n");
      out.write("                    </dd>\r\n");
      out.write("                    <div style=\"clear:both;\"></div>\r\n");
      out.write("                </dl>\r\n");
      out.write("                <div class=\"ord-dai f-l\">\r\n");
      out.write("                \t<p>待付款<span>1</span></p>\r\n");
      out.write("                \t<p>待发货<span>1</span></p>\r\n");
      out.write("                \t<p>待收货<span>1</span></p>\r\n");
      out.write("                \t<p>待评价<span>1</span></p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"clear:both;\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"order-md\">\r\n");
      out.write("            \t<div class=\"md-tit\">\r\n");
      out.write("                \t<h3>我的订单</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"md-hd\">\r\n");
      out.write("                \t<P class=\"md-p1\"><input type=\"checkbox\" name=\"hobby\" value=\"\"></input><span>全选</span></P>\r\n");
      out.write("                    <p class=\"md-p2\">商品信息</p>\r\n");
      out.write("                    <p class=\"md-p3\">规格</p>\r\n");
      out.write("                    <p class=\"md-p4\">单价（元）</p>\r\n");
      out.write("                    <p class=\"md-p5\">金额（元）</p>\r\n");
      out.write("                    <p class=\"md-p6\">操作</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"md-info\">\r\n");
      out.write("                \t<div class=\"dai\">\r\n");
      out.write("                    \t<input type=\"checkbox\" name=\"hobby\" value=\"\"></input><span>待付款</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"dai-con\">\r\n");
      out.write("                    \t<dl class=\"dl1\">\r\n");
      out.write("                        \t<dt>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"hobby\" value=\"\" class=\"f-l\"></input>\r\n");
      out.write("                                <a href=\"#\" class=\"f-l\"><img src=\"images/dai.gif\" /></a>\r\n");
      out.write("                                <div style=\"clear:both;\"></div>\r\n");
      out.write("                            </dt>\r\n");
      out.write("                            <dd>\r\n");
      out.write("                            \t<p>登高阁紫菜肉松鸡蛋卷 海苔蛋卷 糕点江西特产小吃 休闲办公零食</p>\r\n");
      out.write("                                <span>X 1</span>\r\n");
      out.write("                            </dd>\r\n");
      out.write("                            <div style=\"clear:both;\"></div>\r\n");
      out.write("                        </dl>\r\n");
      out.write("                        <div class=\"dai-right f-l\">\r\n");
      out.write("                        \t<P class=\"d-r-p1\">颜色：蓝色<br />尺码：XL</P>\r\n");
      out.write("                            <p class=\"d-r-p2\">¥ 66.00</p>\r\n");
      out.write("                            <p class=\"d-r-p3\">¥ 66.00</p>\r\n");
      out.write("                            <p class=\"d-r-p4\"><a href=\"#\">移入收藏夹</a><br /><a href=\"#\">删除</a><br /><a href=\"#\">付款</a></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div style=\"clear:both;\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"dai-con\">\r\n");
      out.write("                    \t<dl class=\"dl1\">\r\n");
      out.write("                        \t<dt>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"hobby\" value=\"\" class=\"f-l\"></input>\r\n");
      out.write("                                <a href=\"#\" class=\"f-l\"><img src=\"images/dai.gif\" /></a>\r\n");
      out.write("                                <div style=\"clear:both;\"></div>\r\n");
      out.write("                            </dt>\r\n");
      out.write("                            <dd>\r\n");
      out.write("                            \t<p>登高阁紫菜肉松鸡蛋卷 海苔蛋卷 糕点江西特产小吃 休闲办公零食</p>\r\n");
      out.write("                                <span>X 1</span>\r\n");
      out.write("                            </dd>\r\n");
      out.write("                            <div style=\"clear:both;\"></div>\r\n");
      out.write("                        </dl>\r\n");
      out.write("                        <div class=\"dai-right f-l\">\r\n");
      out.write("                        \t<P class=\"d-r-p1\">颜色：蓝色<br />尺码：XL</P>\r\n");
      out.write("                            <p class=\"d-r-p2\">¥ 66.00</p>\r\n");
      out.write("                            <p class=\"d-r-p3\">¥ 66.00</p>\r\n");
      out.write("                            <p class=\"d-r-p4\"><a href=\"#\">移入收藏夹</a><br /><a href=\"#\">删除</a><br /><a href=\"#\">付款</a></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div style=\"clear:both;\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"md-info\">\r\n");
      out.write("                \t<div class=\"dai\">\r\n");
      out.write("                    \t<input type=\"checkbox\" name=\"hobby\" value=\"\"></input><span>待发货</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"dai-con\">\r\n");
      out.write("                    \t<dl class=\"dl1\">\r\n");
      out.write("                        \t<dt>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"hobby\" value=\"\" class=\"f-l\"></input>\r\n");
      out.write("                                <a href=\"#\" class=\"f-l\"><img src=\"images/dai.gif\" /></a>\r\n");
      out.write("                                <div style=\"clear:both;\"></div>\r\n");
      out.write("                            </dt>\r\n");
      out.write("                            <dd>\r\n");
      out.write("                            \t<p>登高阁紫菜肉松鸡蛋卷 海苔蛋卷 糕点江西特产小吃 休闲办公零食</p>\r\n");
      out.write("                                <span>X 1</span>\r\n");
      out.write("                            </dd>\r\n");
      out.write("                            <div style=\"clear:both;\"></div>\r\n");
      out.write("                        </dl>\r\n");
      out.write("                        <div class=\"dai-right f-l\">\r\n");
      out.write("                        \t<P class=\"d-r-p1\">颜色：蓝色<br />尺码：XL</P>\r\n");
      out.write("                            <p class=\"d-r-p2\">¥ 66.00</p>\r\n");
      out.write("                            <p class=\"d-r-p3\">¥ 66.00</p>\r\n");
      out.write("                            <p class=\"d-r-p4\" style=\"margin-top:20px;\"><a href=\"#\">移入收藏夹</a><br /><a href=\"#\">删除</a></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div style=\"clear:both;\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"md-info\">\r\n");
      out.write("                \t<div class=\"dai\">\r\n");
      out.write("                    \t<input type=\"checkbox\" name=\"hobby\" value=\"\"></input><span>待收货</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"dai-con\">\r\n");
      out.write("                    \t<dl class=\"dl1\">\r\n");
      out.write("                        \t<dt>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"hobby\" value=\"\" class=\"f-l\"></input>\r\n");
      out.write("                                <a href=\"#\" class=\"f-l\"><img src=\"images/dai.gif\" /></a>\r\n");
      out.write("                                <div style=\"clear:both;\"></div>\r\n");
      out.write("                            </dt>\r\n");
      out.write("                            <dd>\r\n");
      out.write("                            \t<p>登高阁紫菜肉松鸡蛋卷 海苔蛋卷 糕点江西特产小吃 休闲办公零食</p>\r\n");
      out.write("                                <span>X 1</span>\r\n");
      out.write("                            </dd>\r\n");
      out.write("                            <div style=\"clear:both;\"></div>\r\n");
      out.write("                        </dl>\r\n");
      out.write("                        <div class=\"dai-right f-l\">\r\n");
      out.write("                        \t<P class=\"d-r-p1\" style=\" position:relative;top:-20px;\">颜色：蓝色<br />尺码：XL</P>\r\n");
      out.write("                            <p class=\"d-r-p2\" style=\"top:-43px;\">¥ 66.00</p>\r\n");
      out.write("                            <p class=\"d-r-p3\" style=\"top:-43px;\">¥ 66.00</p>\r\n");
      out.write("                            <p class=\"d-r-p4\"><a href=\"#\">移入收藏夹</a><br /><a href=\"#\">删除</a><br /><a href=\"#\">确认收货</a><br /><a href=\"JavaScript:;\" ckwl=\"\">查看物流</a></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div style=\"clear:both;\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"md-info\">\r\n");
      out.write("                \t<div class=\"dai\">\r\n");
      out.write("                    \t<input type=\"checkbox\" name=\"hobby\" value=\"\"></input><span>待评价</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"dai-con\">\r\n");
      out.write("                    \t<dl class=\"dl1\">\r\n");
      out.write("                        \t<dt>\r\n");
      out.write("                                <input type=\"checkbox\" name=\"hobby\" value=\"\" class=\"f-l\"></input>\r\n");
      out.write("                                <a href=\"#\" class=\"f-l\"><img src=\"images/dai.gif\" /></a>\r\n");
      out.write("                                <div style=\"clear:both;\"></div>\r\n");
      out.write("                            </dt>\r\n");
      out.write("                            <dd>\r\n");
      out.write("                            \t<p>登高阁紫菜肉松鸡蛋卷 海苔蛋卷 糕点江西特产小吃 休闲办公零食</p>\r\n");
      out.write("                                <span>X 1</span>\r\n");
      out.write("                            </dd>\r\n");
      out.write("                            <div style=\"clear:both;\"></div>\r\n");
      out.write("                        </dl>\r\n");
      out.write("                        <div class=\"dai-right f-l\">\r\n");
      out.write("                        \t<P class=\"d-r-p1\">颜色：蓝色<br />尺码：XL</P>\r\n");
      out.write("                            <p class=\"d-r-p2\">¥ 66.00</p>\r\n");
      out.write("                            <p class=\"d-r-p3\">¥ 66.00</p>\r\n");
      out.write("                            <p class=\"d-r-p4\" style=\"margin-top:20px;\"><a href=\"#\">移入收藏夹</a><br /><a href=\"#\">删除</a></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div style=\"clear:both;\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!--分页-->\r\n");
      out.write("                <div class=\"paging\">\r\n");
      out.write("            \t<div class=\"pag-left f-l\">\r\n");
      out.write("                \t<a href=\"#\" class=\"about left-r f-l\"><</a>\r\n");
      out.write("                    <ul class=\"left-m f-l\">\r\n");
      out.write("                    \t<li><a href=\"#\">1</a></li>\r\n");
      out.write("                        <li class=\"current\"><a href=\"#\">2</a></li>\r\n");
      out.write("                        <li><a href=\"#\">3</a></li>\r\n");
      out.write("                        <li><a href=\"#\">4</a></li>\r\n");
      out.write("                        <li><a href=\"#\">5</a></li>\r\n");
      out.write("                        <li><a href=\"#\">6</a></li>\r\n");
      out.write("                        <li><a href=\"#\">...</a></li>\r\n");
      out.write("                        <li><a href=\"#\">100</a></li>\r\n");
      out.write("                        <div style=\"clear:both;\"></div>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                \t<a href=\"#\" class=\"about left-l f-l\">></a>\r\n");
      out.write("                    <div style=\"clear:both;\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            \t<div class=\"pag-right f-l\">\r\n");
      out.write("                \t<div class=\"jump-page f-l\">\r\n");
      out.write("                        到第<input type=\"text\" />页\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"f-l\">确定</button>\r\n");
      out.write("                    <div style=\"clear:both;\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"clear:both;\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("                <div class=\"md-ft\">\r\n");
      out.write("                \t<P class=\"md-p1\"><input type=\"checkbox\" name=\"hobby\" value=\"\"></input><span>全选</span></P>\r\n");
      out.write("                    <a href=\"#\">删除</a>\r\n");
      out.write("                    <a href=\"#\">加入收藏夹<span>（此处始终在屏幕下方）</span></a>\r\n");
      out.write("                    <button>结算</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"clear:both;\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "bottom.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!--查看物流 弹窗-->\r\n");
      out.write("    <div class=\"view-logistics\">\r\n");
      out.write("    \t<div class=\"view-bg\"></div>\r\n");
      out.write("        <div class=\"view-con\">\r\n");
      out.write("        \t<div class=\"view-tit\">\r\n");
      out.write("            \t<h3>物流信息</h3>\r\n");
      out.write("                <a href=\"JavaScript:;\" guanbi=\"\">\r\n");
      out.write("                \t<img src=\"images/close-select-city.gif\" />\r\n");
      out.write("                </a>\r\n");
      out.write("                <div style=\"clear:both;\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"view-bd\">\r\n");
      out.write("            \t<ul>\r\n");
      out.write("                \t<li class=\"bd-pdl-li after\"><span>1</span>2015-08-06　周四　　14:06:53您的订单开始处理</li>\r\n");
      out.write("                \t<li class=\"after\"><span>2</span>14:08:44您的订单待配货</li>\r\n");
      out.write("                \t<li><span>3</span>14:16:04您的包裹已出库</li>\r\n");
      out.write("                \t<li><span>4</span>14:16:03商家正通知快递公司揽件</li>\r\n");
      out.write("                \t<li><span>5</span>21:47:54【惠州市】圆通速递 广东省惠州市惠东县收件员 已揽件</li>\r\n");
      out.write("                \t<li class=\"bd-pdb-li\"><span>6</span>22:13:51广东省惠州市惠东县公司 已发出</li>\r\n");
      out.write("                    <li class=\"bd-pdl-li\"><span>7</span>2015-08-07　周五　　04:57:33广州转运中心公司 已收入</li>\r\n");
      out.write("                \t<li><span>8</span>04:58:54广州转运中心公司 已发出</li>\r\n");
      out.write("                \t<li><span>9</span>2015-08-08周六22:46:43重庆转运中心公司 已收入</li>\r\n");
      out.write("                \t<li class=\"bd-pdb-li\"><span>10</span>23:01:49【重庆市】重庆转运中心 已发出</li>\r\n");
      out.write("                    <li class=\"bd-pdl-li\"><span>11</span>2015-08-09　周日　　00:57:11【重庆市】快件已到达 重庆市南岸区</li>\r\n");
      out.write("                \t<li><span>12</span>11:14:52重庆市南岸区 已收入</li>\r\n");
      out.write("                \t<li><span>13</span>11:14:52【重庆市】重庆市南岸区派件员：李天生 13330284757正在为您派件</li>\r\n");
      out.write("                \t<li class=\"bd-bd-li\"><span>14</span>15:53:14【重庆市】重庆市南岸区公司 已签收 签收人：保安，感谢使用圆通速递，期待再次为您服务</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("                <p class=\"sign\">您的包裹已被签收！</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
