/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.31
 * Generated at: 2018-09-01 06:35:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class my_005fmessage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>个人消息</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/shopping-mall-index.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/zhonglin.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "top.jsp", out, false);
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    \r\n");
      out.write("    \t<div class=\"personal-r f-r\">\r\n");
      out.write("        \t<div class=\"personal-right\">\r\n");
      out.write("                <div class=\"personal-r-tit\">\r\n");
      out.write("                    <h3>消息中心</h3>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"theme\">\r\n");
      out.write("                    <p class=\"th-p1 f-l\">\r\n");
      out.write("                        <input type=\"checkbox\" value=\"\" name=\"hobby\"></input>\r\n");
      out.write("                        <span>选择</span>\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"th-p2 f-l\">\r\n");
      out.write("                        <img src=\"images/th-wenjian-tu.gif\" />\r\n");
      out.write("                    </p>\r\n");
      out.write("                    <p class=\"th-p3 f-l\">主题</p>\r\n");
      out.write("                    <p class=\"th-p4 f-l\">时间</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"per-info\">\r\n");
      out.write("                    <p class=\"p-top\">今天（2封）</p>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <input type=\"checkbox\" value=\"\" name=\"hobby\"></input>\r\n");
      out.write("                            <p class=\"p-tu f-l\"><img src=\"images/th-wenjian-tu.gif\" /></p>\r\n");
      out.write("                            <a href=\"#\" class=\"p-font f-l\">亲爱的客户，欢迎注册外贸下单网站.....</a>\r\n");
      out.write("                            <p class=\"p-time f-l\">2008年8月8日</p>\r\n");
      out.write("                            <div style=\"clear:both;\"></div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <input type=\"checkbox\" value=\"\" name=\"hobby\"></input>\r\n");
      out.write("                            <p class=\"p-tu f-l\"><img src=\"images/th-wenjian-tu2.gif\" /></p>\r\n");
      out.write("                            <a href=\"#\" class=\"p-font p-font1 f-l\">亲爱的客户，欢迎注册外贸下单网站.....</a>\r\n");
      out.write("                            <p class=\"p-time f-l\">2008年8月8日</p>\r\n");
      out.write("                            <div style=\"clear:both;\"></div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"per-info\">\r\n");
      out.write("                    <p class=\"p-top\">上周（2封）</p>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <input type=\"checkbox\" value=\"\" name=\"hobby\"></input>\r\n");
      out.write("                            <p class=\"p-tu f-l\"><img src=\"images/th-wenjian-tu.gif\" /></p>\r\n");
      out.write("                            <a href=\"#\" class=\"p-font f-l\">亲爱的客户，欢迎注册外贸下单网站.....</a>\r\n");
      out.write("                            <p class=\"p-time f-l\">2008年8月8日</p>\r\n");
      out.write("                            <div style=\"clear:both;\"></div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <input type=\"checkbox\" value=\"\" name=\"hobby\"></input>\r\n");
      out.write("                            <p class=\"p-tu f-l\"><img src=\"images/th-wenjian-tu2.gif\" /></p>\r\n");
      out.write("                            <a href=\"#\" class=\"p-font p-font1 f-l\">亲爱的客户，欢迎注册外贸下单网站.....</a>\r\n");
      out.write("                            <p class=\"p-time f-l\">2008年8月8日</p>\r\n");
      out.write("                            <div style=\"clear:both;\"></div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"per-info\">\r\n");
      out.write("                    <p class=\"p-top\">更早（7封）</p>\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <input type=\"checkbox\" value=\"\" name=\"hobby\"></input>\r\n");
      out.write("                            <p class=\"p-tu f-l\"><img src=\"images/th-wenjian-tu.gif\" /></p>\r\n");
      out.write("                            <a href=\"#\" class=\"p-font f-l\">亲爱的客户，欢迎注册外贸下单网站.....</a>\r\n");
      out.write("                            <p class=\"p-time f-l\">2008年8月8日</p>\r\n");
      out.write("                            <div style=\"clear:both;\"></div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <input type=\"checkbox\" value=\"\" name=\"hobby\"></input>\r\n");
      out.write("                            <p class=\"p-tu f-l\"><img src=\"images/th-wenjian-tu.gif\" /></p>\r\n");
      out.write("                            <a href=\"#\" class=\"p-font f-l\">亲爱的客户，欢迎注册外贸下单网站.....</a>\r\n");
      out.write("                            <p class=\"p-time f-l\">2008年8月8日</p>\r\n");
      out.write("                            <div style=\"clear:both;\"></div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <input type=\"checkbox\" value=\"\" name=\"hobby\"></input>\r\n");
      out.write("                            <p class=\"p-tu f-l\"><img src=\"images/th-wenjian-tu.gif\" /></p>\r\n");
      out.write("                            <a href=\"#\" class=\"p-font f-l\">亲爱的客户，欢迎注册外贸下单网站.....</a>\r\n");
      out.write("                            <p class=\"p-time f-l\">2008年8月8日</p>\r\n");
      out.write("                            <div style=\"clear:both;\"></div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <input type=\"checkbox\" value=\"\" name=\"hobby\"></input>\r\n");
      out.write("                            <p class=\"p-tu f-l\"><img src=\"images/th-wenjian-tu.gif\" /></p>\r\n");
      out.write("                            <a href=\"#\" class=\"p-font f-l\">亲爱的客户，欢迎注册外贸下单网站.....</a>\r\n");
      out.write("                            <p class=\"p-time f-l\">2008年8月8日</p>\r\n");
      out.write("                            <div style=\"clear:both;\"></div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <input type=\"checkbox\" value=\"\" name=\"hobby\"></input>\r\n");
      out.write("                            <p class=\"p-tu f-l\"><img src=\"images/th-wenjian-tu2.gif\" /></p>\r\n");
      out.write("                            <a href=\"#\" class=\"p-font p-font1 f-l\">亲爱的客户，欢迎注册外贸下单网站.....</a>\r\n");
      out.write("                            <p class=\"p-time f-l\">2008年8月8日</p>\r\n");
      out.write("                            <div style=\"clear:both;\"></div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <input type=\"checkbox\" value=\"\" name=\"hobby\"></input>\r\n");
      out.write("                            <p class=\"p-tu f-l\"><img src=\"images/th-wenjian-tu2.gif\" /></p>\r\n");
      out.write("                            <a href=\"#\" class=\"p-font p-font1 f-l\">亲爱的客户，欢迎注册外贸下单网站.....</a>\r\n");
      out.write("                            <p class=\"p-time f-l\">2008年8月8日</p>\r\n");
      out.write("                            <div style=\"clear:both;\"></div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <input type=\"checkbox\" value=\"\" name=\"hobby\"></input>\r\n");
      out.write("                            <p class=\"p-tu f-l\"><img src=\"images/th-wenjian-tu2.gif\" /></p>\r\n");
      out.write("                            <a href=\"#\" class=\"p-font p-font1 f-l\">亲爱的客户，欢迎注册外贸下单网站.....</a>\r\n");
      out.write("                            <p class=\"p-time f-l\">2008年8月8日</p>\r\n");
      out.write("                            <div style=\"clear:both;\"></div>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button class=\"per-del\">删除选项</button>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <!--分页-->\r\n");
      out.write("            <div class=\"paging\">\r\n");
      out.write("            \t<div class=\"pag-left f-l\">\r\n");
      out.write("                \t<a href=\"#\" class=\"about left-r f-l\"><</a>\r\n");
      out.write("                    <ul class=\"left-m f-l\">\r\n");
      out.write("                    \t<li><a href=\"#\">1</a></li>\r\n");
      out.write("                        <li class=\"current\"><a href=\"#\">2</a></li>\r\n");
      out.write("                        <li><a href=\"#\">3</a></li>\r\n");
      out.write("                        <li><a href=\"#\">4</a></li>\r\n");
      out.write("                        <li><a href=\"#\">5</a></li>\r\n");
      out.write("                        <li><a href=\"#\">6</a></li>\r\n");
      out.write("                        <li><a href=\"#\">...</a></li>\r\n");
      out.write("                        <li><a href=\"#\">100</a></li>\r\n");
      out.write("                        <div style=\"clear:both;\"></div>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                \t<a href=\"#\" class=\"about left-l f-l\">></a>\r\n");
      out.write("                    <div style=\"clear:both;\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("            \t<div class=\"pag-right f-l\">\r\n");
      out.write("                \t<div class=\"jump-page f-l\">\r\n");
      out.write("                        到第<input type=\"text\" />页\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <button class=\"f-l\">确定</button>\r\n");
      out.write("                    <div style=\"clear:both;\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"clear:both;\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"clear:both;\"></div>\r\n");
      out.write("    \t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "bottom.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
