/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.31
 * Generated at: 2018-09-01 07:21:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.home;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>注册</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"css/shopping-mall-index.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/zhonglin.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!--top 开始-->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "index_top.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!--内容开始-->\r\n");
      out.write("    <div class=\"password-con registered\">\r\n");
      out.write("    \t<div class=\"psw\">\r\n");
      out.write("        \t<p class=\"psw-p1\">用户名</p>\r\n");
      out.write("            <input type=\"text\" placeholder=\"HR了\" />\r\n");
      out.write("            <span class=\"dui\"></span>\r\n");
      out.write("        </div>\r\n");
      out.write("    \t<div class=\"psw\">\r\n");
      out.write("        \t<p class=\"psw-p1\">输入密码</p>\r\n");
      out.write("            <input type=\"text\" placeholder=\"请输入密码\" />\r\n");
      out.write("            <span class=\"cuo\">密码由6-16的字母、数字、符号组成</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    \t<div class=\"psw\">\r\n");
      out.write("        \t<p class=\"psw-p1\">确认密码</p>\r\n");
      out.write("            <input type=\"text\" placeholder=\"请再次确认密码\" />\r\n");
      out.write("            <span class=\"cuo\">密码不一致，请重新输入</span>\r\n");
      out.write("        </div>\r\n");
      out.write("    \t<div class=\"psw psw2\">\r\n");
      out.write("        \t<p class=\"psw-p1\">手机号/邮箱</p>\r\n");
      out.write("            <input type=\"text\" placeholder=\"请输入手机/邮箱验证码\" />\r\n");
      out.write("            <button>获取短信验证码</button>\r\n");
      out.write("        </div>\r\n");
      out.write("    \t<div class=\"psw psw3\">\r\n");
      out.write("        \t<p class=\"psw-p1\">验证码</p>\r\n");
      out.write("            <input type=\"text\" placeholder=\"请输入手机/邮箱验证码\" />\r\n");
      out.write("        </div>\r\n");
      out.write("    \t<div class=\"psw psw3\">\r\n");
      out.write("        \t<p class=\"psw-p1\">验证码</p>\r\n");
      out.write("            <input type=\"text\" placeholder=\"请输入验证码\" />\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"yanzhentu\">\r\n");
      out.write("        \t<div class=\"yz-tu f-l\">\r\n");
      out.write("            \t<img src=\"images/psw-yanzhengtu.gif\" />\r\n");
      out.write("            </div>\r\n");
      out.write("            <p class=\"f-l\">看不清？<a href=\"#\">换张图</a></p>\r\n");
      out.write("            <div style=\"clear:both;\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"agreement\">\r\n");
      out.write("        \t<input type=\"checkbox\" name=\"hobby\"></input>\r\n");
      out.write("            <p>我有阅读并同意<span>《宅客微购网站服务协议》</span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <button class=\"psw-btn\">立即注册</button>\r\n");
      out.write("        <p class=\"sign-in\">已有账号？请<a href=\"#\">登录</a></p>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <!--底部服务-->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "bottom.jsp", out, false);
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
